### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by FlYos** [dupoxy/go-tour-fr#18]
Context: https://go-tour-fr.appspot.com/basics/5

Lors de l'exécution du code (sans modification), j'ai cette erreur en retour:
{"compile_errors":"can't load package: package main: \nprog.go:1:1: expected 'package', found 'EOF'\n","output":""}

Alors que sur la version EN tout fonctionne bien

**Comment by dupoxy** [comment]
C'est enfin fixé.
re-deployed using the updated version of the tools repository golang/go/issues/15693
