### ISSUE TITLE
Aucun retour de compilation/exécution

### ISSUE THREAD

**Issue by Thaelz** [dupoxy/go-tour-fr#19]
Contexte: https://go-tour-fr.appspot.com/basics/3

Bonjour,

1. Version de Go: celle utilisée sur le serveur (online)
2. OS & Architecture: Windows 10 x64
3. Action: Compilation du programme proposé à l'URL indiquée
4. Résultat attendu: Je m'attendais à voir l'erreur attendue ou le print attendu en corrigeant l'erreur.
5. Résultat obtenu: Aucun retour dans l'encart console avec ou sans erreur.

L'erreur de compilation attendue n'apparait pas dans l'encart de sortie/entrée (comme tout autre message durant l'exécution d'ailleurs) contrairement à la version anglaise, testé sous Opera et Edge. Aucun message d'erreur dans la console du navigateur pour vous aider.
Lien vers la version anglaise (fonctionnelle) : https://tour.golang.org/basics/3

**Comment by alebaffa** [comment]
@dupoxy est-ce que vous allez maintenir ce repo? Sinon ça serait mieux de demander a quelqu'un d'autre de la communauté de le faire. Ce problème de compilation est la depuis plusieurs mois. Faites-nous savoir, s'il vous plait. Merci!

**Comment by dupoxy** [comment]
duplicate of #18

>est-ce que vous allez maintenir ce repo?

Quand je trouve le temps. Si quelqu'un d'autre de la communauté veut aider c'est avec plaisir.
