### ISSUE TITLE
go-tour-fr.appspot.com : Error communicating with remote server

### ISSUE THREAD

**Issue by theblackhole** [dupoxy/go-tour-fr#20]
Bonjour,

Sur https://go-tour-fr.appspot.com/welcome/1 il y a un problème à l'exécution :
```
Error communicating with remote server.
Program exited.
```

Le projet est-il toujours maintenu ?

**Comment by dupoxy** [comment]
duplicate of #18 

> Le projet est-il toujours maintenu ?

quand je trouve le temps
