### ISSUE TITLE
Erreur de français

### ISSUE THREAD

**Issue by HugoLafleur** [dupoxy/go-tour-fr#22]
Context: http://127.0.0.1:3999/basics/7

Est:
...dans des fonctions courte, comme avec l'exemple montré ici. Ils peuvent nuire à la lisibilité de fonctions plus grande....

Devrait être:
...dans des fonctions courtes, comme avec l'exemple montré ici. Ils peuvent nuire à la lisibilité de fonctions plus grandes....

**Comment by dupoxy** [comment]
fixed in a28001b
