### ISSUE TITLE
Corrections orthographique

### ISSUE THREAD

**Issue by bighandsFR** [dupoxy/go-tour-fr#35]
Context: https://go-tour-fr.appspot.com/basics/7
Corrections orthographique

Il y a des problèmes d'accords de grammaire.
Je propose de corriger le texte comme ceci :

_Les valeurs de retour de Go peuvent être **nommées**. Si c'est le cas, elles sont **traitées** comme des variables définies dans le haut de la fonction._

_Ces noms doivent être utilisés pour documenter la signification des valeurs de retour._

_Une déclaration return sans arguments renvoie les valeurs de retour **nommées**. C'est ce qu'on appelle un retour « nu »._

_Des déclarations de retour nus doivent être **utilisées** uniquement dans des fonctions courte, comme avec l'exemple montré ici. Ils peuvent nuire à la lisibilité de fonctions plus grande._

**Comment by dupoxy** [comment]
fixed in a28001b
