### ISSUE TITLE
"cannot find package error" on http://go-tour-fr.appspot.com/methods/11

### ISSUE THREAD

**Issue by diodfr** [dupoxy/go-tour-fr#7]
HI,
I've got a "cannot find package error" on http://go-tour-fr.appspot.com/methods/11 when I try to run the program. It works on the english version.

    /tmp/sandbox324968546/main.go:3:8: cannot find package "github.com/dupoxy/go-tour-fr/reader/" in any of:
    /usr/src/go/src/github.com/dupoxy/go-tour-fr/reader (from $GOROOT)
    /go/src/github.com/dupoxy/go-tour-fr/reader (from $GOPATH)

Thanks for your work.

**Comment by dupoxy** [comment]
closed by commit 8b6c0dc
